name: parsefold_mhc
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - python=3.*
  - muscle=5.1
  - blast=2.10
  - biopython
  - modeller
  - numpy
  - pandas
  - pip
  - freesasa
  - tensorflow=2.11.0
  - tensorflow-estimator=2.11.0
  - scipy=1.7.0
  - pip:
    - -r pip_requirements.txt

